# Site settings
url: https://lufevida.github.io
baseurl: /html5up-future-imperfect
copyright: Untitled
title: Future Imperfect
tagline: by HTML5 UP
description: Another fine responsive site template by HTML5 UP
about: Write here a couple sentences about the author.

# Contact information
email: name@provider.com
twitter: username
facebook: username
instagram: username