# Site settings
url: https://lufevida.github.io
baseurl: /html5up-future-imperfect
copyright: Untitled
title: Future Imperfect
tagline: by HTML5 UP
about: Write here a couple sentences about the author.